server:
  port: 80
  tomcat:
    max-http-post-size: 1048000

wechat:
  mpAppId: wx2881e3092b5ab7e3
  mpAppSecret: f283bbf9e1e9ca8fd53062fe8d594aa2
  mpToken: xfp
  mpAesKey:

spring:
  application:
    name: xiaodao